name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: "50051"

jwt:
  key: 'X$t0xUN@reBoKoqp'
#
redis:
  host: '172.30.70.200'
  port: 6379
  expire: 60
#
#sms:
#  key: ''
#  secret: ''


